Marketplace/Controllers/BidController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Collections.Generic;
using Marketplace.Models;
using Marketplace.Data;
using Marketplace.Services;
using System;


namespace Marketplace.Controllers
{
    [Authorize]
    public class BidController : Controller
    {  
        public BidService BidService;
        public IEnumerable<BidModel> Bids { get; private set; }

        private readonly UserManager<InstructorModel> _userManager;

        public BidController(BidService bid, UserManager<InstructorModel> userManager)
        {
            BidService = bid;
            _userManager = userManager;
        }
        
        public IActionResult Index()
        {
            Bids = BidService.GetBids();
            return View(Bids);
        }

        public IActionResult Create(int moduleId)
        {
            TempData["module"] = moduleId;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BidModel bid)
        {
            int moduleId;
            var user = await _userManager.GetUserAsync(User);
            if(TempData["module"] != null)
            {
                moduleId = (int)TempData["module"];
                TempData["module"] = null;
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }

            bid.ModuleModelId = moduleId;  
            bid.InstructorBiddedId = user.Id;
            bid.InstructorBidded = user.Name;
            BidService.CreateBid(bid);
            
            
            
            return RedirectToAction("Index", "Instructor");
        }

        public IActionResult Edit(int bidId)
        {
            BidModel bidToEdit = BidService.getBidById(bidId);
            return View(bidToEdit);
        }

        [HttpPost]
        public IActionResult Edit(BidModel editedBid)
        {
            
            BidService.EditBid(editedBid);
            return RedirectToAction("Index", "Instructor");
        }
        public IActionResult Delete(int bidId)
        {
            BidService.DeleteBid(bidId);
            return RedirectToAction("Index", "Instructor");
        }


    }
}

Marketplace/Controllers/ModuleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Collections.Generic;
using Marketplace.Models;
using Marketplace.Data;
using Marketplace.Services;


namespace Marketplace.Controllers
{
    public class ModuleController : Controller
    {  
        public ModuleInstructorListService ModuleService;
        public IEnumerable<ModuleModel> Modules { get; private set; }

        public ModuleController(ModuleInstructorListService module)
        {
            ModuleService = module;
        }

        public IActionResult Details(int moduleId)
        {
            ModuleModel module = ModuleService.GetModuleById(moduleId);
            return View(module);
        }
        

    }
}

Marketplace/Views/InstructorModule/Details.cshtml
@model Marketplace.Models.ModuleModel

@{
    var module = Model;
    ViewData["Title"] = module.ModuleName;
}

<div class="text-center">
    <h4 class="display-4">@Html.DisplayNameFor(model => model.ModuleName)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModuleCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModuleCode)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicYear)
        </dd>
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lecturers)
        </dt>
        @* @foreach (var lecturer in Model.Lecturers)
        {
            <dd class = "col-sm-10">@lecturer.ToString()</dd>
        } *@

        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KeywordsAssociatedWithModule)
        </dt>
        <dd class = "col-sm-10"></dd> *@
        @* @foreach (var keyword in Model.KeywordsAssociatedWithModule)
        {
            <p>@keyword </p>
        } *@
        </dd>
    </dl>
</div>

Marketplace/Views/InstructorModule/Index.cshtml
@model IEnumerable<Marketplace.Models.ModuleModel>

@{
    ViewData["Title"] = "Modules";
}

<div class="text-center">
    <h1 class="display-4">Select module to create a bid</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModuleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AcademicYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semester)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model)
{       
    <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @* <a asp-controller="Bid" asp-action="Create" asp-route-id="@item.Id">Bid</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                @Html.ActionLink("Bid", "Create", "Bid", new { moduleId = item.Id })
                @Html.ActionLink("Details", "Details", "Module", new { moduleId = item.Id })
            </td>
        </tr>
}