Marketplace/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Collections.Generic;
using Marketplace.Models;
using Marketplace.Data;
using Marketplace.Services;
using System;


namespace Marketplace.Controllers
{
    [Authorize]
    public class InstructorController : Controller
    {  
        public InstructorService InstructorService;
        private readonly UserManager<InstructorModel> _userManager;

        public InstructorController(InstructorService InstructorService, UserManager<InstructorModel> userManager)
        {
            this.InstructorService = InstructorService;
            _userManager = userManager;
        }
        
        public async Task<IActionResult> Index()
        {
            //List bids created by user
            var user = await _userManager.GetUserAsync(User);
            Console.WriteLine("User Id is : " + user.Id);
            ViewBag.AcceptedBids = InstructorService.GetAcceptedBids(user.Id);
            ViewBag.RejectedBids = InstructorService.GetRejectedBids(user.Id);
            ViewBag.PendingBids = InstructorService.GetPendingBids(user.Id);
            return View();
        }

    }
}

Marketplace/Controllers/ModuleInstructorListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Collections.Generic;
using Marketplace.Models;
using Marketplace.Data;
using Marketplace.Services;


namespace Marketplace.Controllers
{
    
    public class InstructorModuleController : Controller
    {  
        public ModuleInstructorListService ModuleService;
        public IEnumerable<ModuleModel> Modules { get; private set; }

        public InstructorModuleController(ModuleInstructorListService module)
        {
            ModuleService = module;
        }
        
        public IActionResult Index()
        {
            Modules = ModuleService.GetModules();
            return View(Modules);
        }

        public IActionResult Details(int moduleId)
        {
            ModuleModel module = ModuleService.GetModuleById(moduleId);
            return View(module);
        }
        [Authorize]
        public IActionResult Create(ModuleModel module)
        {
            return RedirectToAction("Create", "Bid", new { moduleId = module.Id });
        }
        

    }
}

Marketplace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marketplace</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/shared.css" />
    
</head>
<body>
    <header>
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/tcd-logo.png" alt="TCD Logo"></a>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 navbar-custom">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Administrator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="InstructorModule" asp-action="Index">Modules</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Marketplace - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>